license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="SKD"
logoFile="dinamyc_combat.png"
description='''
Easy, spectacular and fun melee combat system from Minecraft Dungeons.
Replica of BetterCombat for Minecraft 1.21.5.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="player_animation_core"
    type="required"
    versionRange="[0.0.0-beta.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cloth_config"
    type="required"
    versionRange="[26.1,)"
    ordering="AFTER"
    side="BOTH"
